### ISSUE TITLE
进入页面提示 create stream failed!

### ISSUE THREAD

**Issue by zyw61483** [LingyuCoder/SkyRTC-demo#10]
进入页面提示 create stream failed! 不能视频聊天，也不能文字聊天，是怎么回事呢？

**Comment by zyw61483** [comment]
参照issue #6 的回答，配了ssl，ok了。

**Comment by zyw61483** [comment]
今天突然发现 用firefox可以不用配SSL

**Comment by zero863** [comment]
您好，您是否实现了跨局域网通信呢？如果是能否指导下我，同时想请您指导下ssl如何配置使用？
